"""initial schema

Revision ID: bec01fc2ff72
Revises: 
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'bec01fc2ff72'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_index('ix_api_keys_tenant', 'api_keys', ['tenant_id'], unique=False)
    op.create_table('attrition_models',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm', sa.String(length=60), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('positives', sa.Integer(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('decision_ledger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('workflow', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=200), nullable=False),
    sa.Column('agent', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('approver', sa.String(length=200), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sequence', name='uq_ledger_tenant_sequence')
    )
    op.create_index('ix_ledger_subject', 'decision_ledger', ['tenant_id', 'subject_id'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('autonomous_actions', sa.JSON(), nullable=False),
    sa.Column('forbidden_actions', sa.JSON(), nullable=False),
    sa.Column('readable_domains', sa.JSON(), nullable=False),
    sa.Column('confidence_floor', sa.Float(), nullable=False),
    sa.Column('approver_role', sa.String(length=100), nullable=False),
    sa.Column('escalation_role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('workflow_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('workflow', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=200), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_workflow_runs_subject', 'workflow_runs', ['tenant_id', 'subject_id'], unique=False)
    op.create_index('ix_workflow_runs_tenant', 'workflow_runs', ['tenant_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('approver', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.run_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_key', name='uq_run_step')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_steps')
    op.drop_index('ix_workflow_runs_tenant', table_name='workflow_runs')
    op.drop_index('ix_workflow_runs_subject', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_table('tenants')
    op.drop_index('ix_ledger_subject', table_name='decision_ledger')
    op.drop_table('decision_ledger')
    op.drop_table('attrition_models')
    op.drop_index('ix_api_keys_tenant', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
